In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\kevin\anaconda3\envs\campus\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\kevin\anaconda3\envs\campus\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\Users\kevin\anaconda3\envs\campus\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ------------------- -------------------- 4.7/9.8 MB 23.8 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 23.6 MB/s  0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import numpy as np # 내부적으로 numpy 사용하므로 반드시 함께 사용

In [6]:
x=[1,2,3,4,5]
series_x=pd.Series(x) # 대소문자구분
series_x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
arr_x=np.array(x)
series_x=pd.Series(arr_x)
series_x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
series_x[0]
series_x[1:3]
series_x[::-1] # 뒤집기
series_x[series_x>3]

3    4
4    5
dtype: int64

In [11]:
series_x.index

RangeIndex(start=0, stop=5, step=1)

In [12]:
series_x.values # list로 만들었음에도 numpy의 array로 변환 - pandas 자체에서 내부적으로 numpy 사용

array([1, 2, 3, 4, 5])

In [22]:
x=[1,2,3,4,5]
sr_x=pd.Series(x,index=['a','b','c','d','e'])
sr_x.index
print(sr_x['a'])
# print(sr_x[0]) # 묵시적 인덱스 접근 - 최신 버전에선 불허
sr_x[['b','c']] # 한번에 여러 값 접근
sr_x[sr_x>2] # 3 이상 색인
sr_x.a # 인덱스명 자체를 속성으로 취급 (지양)

1

np.int64(1)

In [27]:
x = {"수학":90, "영어":80, "과학":95, "미술":80}
sr_x = pd.Series(x)

sr_x
sr_x['영어':'과학'] # 여기선 slicing 시 시작값과 끝값이 포함됨

영어    80
과학    95
dtype: int64

In [29]:
student_1 = {"수학": 90, "영어": 80, "과학": 95, "미술": 80}
student_2 = {"수학": 70, "영어": 90, "과학": 100, "미술": 70}

index_1  =  ['홍길동' for i in range(len(student_1))] + ['이몽룡' for i in range(len(student_2))]
index_2=list(student_1.keys())+list(student_2.keys())
index_1,index_2

values_all=list(student_1.values())+list(student_2.values())
values_all

[90, 80, 95, 80, 70, 90, 100, 70]

In [31]:
sr_scores=pd.Series(values_all,index=[index_1,index_2])
sr_scores

홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64

In [32]:
x=[1,None,2,None,3,4,None]
y=pd.Series(x)

y # None이라는 다른 자료형이 입력되면서 출력이 float로 변환

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

In [33]:
y.sum(),y.min(),y.max() # 결측값은 자동으로 제외

(np.float64(10.0), np.float64(1.0), np.float64(4.0))

In [35]:
y.isnull().sum() # 결측치(null) 갯수 합

np.int64(3)

In [36]:
y.dropna() # 결측치 제거

0    1.0
2    2.0
4    3.0
5    4.0
dtype: float64

In [37]:
y.fillna(0) # 결측치 채우기

0    1.0
1    0.0
2    2.0
3    0.0
4    3.0
5    4.0
6    0.0
dtype: float64

In [38]:
x = pd.Series([1, 2, 3])
y = pd.Series([4, 5, 6])
z = pd.Series([7, 8, 9])

In [43]:
sr_xyz=pd.concat([x,y,z], axis=1, ignore_index=True)
sr_xyz
# verify_integrity=True 동일 인덱스 번호 있으면 오류 발생

   0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [44]:
x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([6, 7, 8, 9, 0])

In [45]:
x.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [48]:
# 실습1
np.random.seed(5)
x=[np.nan,1,2,3,4,5]
y=pd.Series(
    [
        x[np.random.randint(0,6)] for i in range (20) # x 값들로 랜덤 출력
    ]
) # 들여쓰기를 생활화하면 괄호 구분이 쉬움
y

0     3.0
1     5.0
2     NaN
3     1.0
4     NaN
5     4.0
6     3.0
7     NaN
8     NaN
9     4.0
10    1.0
11    5.0
12    NaN
13    3.0
14    4.0
15    5.0
16    3.0
17    1.0
18    4.0
19    5.0
dtype: float64

In [50]:
y.isnull().sum()
y.count() # ==notnull().sum() 결측치 이외 카운트

np.int64(15)

In [51]:
drop_y=y.dropna(ignore_index=True)
drop_y

0     3.0
1     5.0
2     1.0
3     4.0
4     3.0
5     4.0
6     1.0
7     5.0
8     3.0
9     4.0
10    5.0
11    3.0
12    1.0
13    4.0
14    5.0
dtype: float64

In [52]:
mean_y=y.mean()
fill_y=y.fillna(mean_y)
fill_y

0     3.0
1     5.0
2     3.4
3     1.0
4     3.4
5     4.0
6     3.0
7     3.4
8     3.4
9     4.0
10    1.0
11    5.0
12    3.4
13    3.0
14    4.0
15    5.0
16    3.0
17    1.0
18    4.0
19    5.0
dtype: float64

In [55]:
# DataFrame
sales_data = {
'연도':[2015, 2016, 2017, 2018, 2019, 2020],
'판매량':[103, 70, 130, 160, 190, 230],
'매출':[500000, 300000, 400000, 550000, 700000, 680000],
'순이익':[370000, 190000, 300000, 480000, 600000, 590000]
}
sales_DF = pd.DataFrame(sales_data)
sales_DF

     연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000

In [56]:
sales_DF['판매량']

0    103
1     70
2    130
3    160
4    190
5    230
Name: 판매량, dtype: int64

In [57]:
sales_DF.iloc[3]

연도       2018
판매량       160
매출     550000
순이익    480000
Name: 3, dtype: int64

In [59]:
pd.DataFrame(sales_data, columns=['판매량','매출','순이익'], index=sales_data['연도'])

      판매량      매출     순이익
2015  103  500000  370000
2016   70  300000  190000
2017  130  400000  300000
2018  160  550000  480000
2019  190  700000  600000
2020  230  680000  590000

In [60]:
sales_DF.set_index('연도')

      판매량      매출     순이익
연도
2015  103  500000  370000
2016   70  300000  190000
2017  130  400000  300000
2018  160  550000  480000
2019  190  700000  600000
2020  230  680000  590000

In [64]:
sales_df_csv=pd.read_csv('sales_data.csv',header=0,index_col=0,encoding='UTF-8')

In [67]:
sales_df_csv.to_csv('sales_data_mod.csv',encoding='UTF-8')
sales_df_csv.reset_index().to_csv('sales_data_mod.csv',index=None,encoding='UTF-8')
pd.read_csv('sales_data_mod.csv')

     연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000

In [70]:
sales_DF['순이익률']=sales_DF['순이익']/sales_DF['매출']
sales_DF

     연도  판매량      매출     순이익      순이익률
0  2015  103  500000  370000  0.740000
1  2016   70  300000  190000  0.633333
2  2017  130  400000  300000  0.750000
3  2018  160  550000  480000  0.872727
4  2019  190  700000  600000  0.857143
5  2020  230  680000  590000  0.867647

In [78]:
def check(n):
    if n>0.8:
        return '높음'
    else:
        return '낮음'

In [80]:
sales_DF['순이익률'].apply(check) # check 함수를 apply

0    낮음
1    낮음
2    낮음
3    높음
4    높음
5    높음
Name: 순이익률, dtype: str

In [83]:
sales_DF['순이익률 비교']=sales_DF['순이익률'].apply(lambda x:'높음' if x>0.8 else '낮음') # lambda - 익명함수
sales_DF

     연도  판매량      매출     순이익      순이익률 순이익률 비교
0  2015  103  500000  370000  0.740000      낮음
1  2016   70  300000  190000  0.633333      낮음
2  2017  130  400000  300000  0.750000      낮음
3  2018  160  550000  480000  0.872727      높음
4  2019  190  700000  600000  0.857143      높음
5  2020  230  680000  590000  0.867647      높음

In [91]:
bool_index=(sales_DF['순이익률 비교']=='높음') & (sales_DF['매출']>600000)
sales_DF[bool_index]

     연도  판매량      매출     순이익      순이익률 순이익률 비교
4  2019  190  700000  600000  0.857143      높음
5  2020  230  680000  590000  0.867647      높음

In [93]:
sales_DF['test'] =sales_DF[bool_index]['매출'] - 50000
sales_DF

     연도  판매량      매출     순이익      순이익률 순이익률 비교      test
0  2015  103  500000  370000  0.740000      낮음       NaN
1  2016   70  300000  190000  0.633333      낮음       NaN
2  2017  130  400000  300000  0.750000      낮음       NaN
3  2018  160  550000  480000  0.872727      높음       NaN
4  2019  190  700000  600000  0.857143      높음  650000.0
5  2020  230  680000  590000  0.867647      높음  630000.0

In [98]:
sales_DF['test1']='test1'
sales_DF['test2']='test2'
sales_DF['test3']='test3'
sales_DF

     연도  판매량      매출     순이익      순이익률 순이익률 비교      test  test2  test3  test1
0  2015  103  500000  370000  0.740000      낮음       NaN  test2  test3  test1
1  2016   70  300000  190000  0.633333      낮음       NaN  test2  test3  test1
2  2017  130  400000  300000  0.750000      낮음       NaN  test2  test3  test1
3  2018  160  550000  480000  0.872727      높음       NaN  test2  test3  test1
4  2019  190  700000  600000  0.857143      높음  650000.0  test2  test3  test1
5  2020  230  680000  590000  0.867647      높음  630000.0  test2  test3  test1

In [99]:
del sales_DF['test1']
sales_DF

     연도  판매량      매출     순이익      순이익률 순이익률 비교      test  test2  test3
0  2015  103  500000  370000  0.740000      낮음       NaN  test2  test3
1  2016   70  300000  190000  0.633333      낮음       NaN  test2  test3
2  2017  130  400000  300000  0.750000      낮음       NaN  test2  test3
3  2018  160  550000  480000  0.872727      높음       NaN  test2  test3
4  2019  190  700000  600000  0.857143      높음  650000.0  test2  test3
5  2020  230  680000  590000  0.867647      높음  630000.0  test2  test3

In [100]:
sales_DF.drop(['test2'],axis=1,inplace=True) # inplace -> 원본에 적용 옵션
# axis=0(기본값) -> 행 삭제, axis=1 -> 열 삭제 (아마도 차원에 해당하는 부분일 듯?)
sales_DF

     연도  판매량      매출     순이익      순이익률 순이익률 비교      test  test3
0  2015  103  500000  370000  0.740000      낮음       NaN  test3
1  2016   70  300000  190000  0.633333      낮음       NaN  test3
2  2017  130  400000  300000  0.750000      낮음       NaN  test3
3  2018  160  550000  480000  0.872727      높음       NaN  test3
4  2019  190  700000  600000  0.857143      높음  650000.0  test3
5  2020  230  680000  590000  0.867647      높음  630000.0  test3

In [ ]:
# DF Multiindex

In [104]:
df = pd.DataFrame(np.random.randint(1, 100, size=(8, 2)),
index=[['A창고','A창고','A창고','A창고','B창고','B창고','B창고','B창고'],
['사과','배','바나나','사과','사과','배','바나나','배']],
columns=['판매','재고'])

df.index.names=['창고명','상품명']
df.groupby('창고명').sum()
df.groupby('상품명').sum()
df.groupby(['창고명','상품명']).sum()

          판매  재고
창고명 상품명
A창고 바나나   90  86
    배     30  34
    사과    87  45
B창고 바나나   10  39
    배    139  49
    사과    95  15

In [106]:
df.sort_values(['판매'],ascending=False).head(3)

         판매  재고
창고명 상품명
B창고 사과   95  15
    배    91  32
A창고 바나나  90  86

In [107]:
df.sort_values(['판매','재고'],ascending=[True,False])

         판매  재고
창고명 상품명
A창고 사과    8  17
B창고 바나나  10  39
A창고 배    30  34
B창고 배    48  17
A창고 사과   79  28
    바나나  90  86
B창고 배    91  32
    사과   95  15

In [ ]:
# 실습2

In [111]:
np.random.seed(5)
df=pd.DataFrame(
    np.random.randint(1,100,size=(15,3)),
    index=[
        ['%d학년'%i for i in range (1,4) for _ in range(5)],
        # ['1학년']*5+['2학년']*5+['3학년']*5
        # ['%d반'%i for i in range(1,6)]
        ['%d반'%i for _ in range(3) for i in range(1,6)] # 반복시키는 순서에 따라 변수 위치를 달리해야
    ],
    columns=['국어','영어','과학'],
)
df

        국어  영어  과학
1학년 1반  79  62  17
    2반  74   9  63
    3반  28  31  81
    4반   8  77  16
    5반  54  81  28
2학년 1반  45  78  76
    2반  66  48  31
    3반  85  87  19
    4반  10  42  63
    5반   2  83  17
3학년 1반  79   6  59
    2반   1  81   5
    3반  37  52  28
    4반  32   3  69
    5반  39  84  20

In [116]:
df['합계']=df[['국어','영어','과학']].sum(axis=1)
df['평균']=df['합계']/3
df

        국어  영어  과학   합계         평균
1학년 1반  79  62  17  158  52.666667
    2반  74   9  63  146  48.666667
    3반  28  31  81  140  46.666667
    4반   8  77  16  101  33.666667
    5반  54  81  28  163  54.333333
2학년 1반  45  78  76  199  66.333333
    2반  66  48  31  145  48.333333
    3반  85  87  19  191  63.666667
    4반  10  42  63  115  38.333333
    5반   2  83  17  102  34.000000
3학년 1반  79   6  59  144  48.000000
    2반   1  81   5   87  29.000000
    3반  37  52  28  117  39.000000
    4반  32   3  69  104  34.666667
    5반  39  84  20  143  47.666667

In [117]:
df.index.names=['학년','반']
df.groupby('학년').sum()

      국어   영어   과학   합계          평균
학년
1학년  243  260  205  708  236.000000
2학년  208  338  206  752  250.666667
3학년  188  226  181  595  198.333333

In [ ]:
# 실습3

In [152]:
df=pd.read_csv('titanic.csv')

In [153]:
df.describe() # include='O'(objects), 'all'(전체) (기본값 - 숫자만)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [154]:
# 1. 결측지 처리를 해주세요. 
# (age -평균값적용, Cabin -N으로, Embarked-N)

df.columns # columns가 많을 경우 수월한 확인을 위해
df['Age']=df['Age'].fillna(df['Age'].mean()) # 결측치에 대해 평균값으로 대입
df['Age'].isnull().sum() # 결측치 제거 확인

np.int64(0)

In [155]:
df['Cabin']=df['Cabin'].fillna('N')
df['Embarked']=df['Embarked'].fillna('N')

df['Cabin'].isnull().sum()
df['Embarked'].isnull().sum()

np.int64(0)

In [156]:
# 2. 성(Sex)별생존자 합을 구해주세요

# df[['Sex','Survived']]
df.groupby('Sex').sum()['Survived']

Sex
female    233
male      109
Name: Survived, dtype: int64

In [157]:
# 3. 클래스(Pclass)별 생존자 합을 구해주세요

df.groupby('Pclass').sum()['Survived']

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [158]:
# 4. 나이(Age)를 활용 유아, 10대, 20대, 30대, 40대, 50대, 60대, 노인의 생존자합을 구해주세요

def get_group(age):
    if age<10:
        return '영유아'
    
    for i in range(1,7):
        if age//10==i:
            return '%d0대'%i

    return '70대 이상'

In [160]:
df['Age_group']=df['Age'].apply(get_group)
df.groupby('Age_group').sum()['Survived']

Age_group
10대        41
20대       129
30대        73
40대        34
50대        20
60대         6
70대 이상      1
영유아        38
Name: Survived, dtype: int64